image: node:6

cache:
  paths:
    - node_modules/
    - public/content

test:
  script:
    - npm install
    - npm test-with-coverage

pages:
  script:
    - npm install
    - npm run sync-content
    - npm run build
    - npm run build:minify
  artifacts:
    paths:
      - public
  only:
    - master
