image: node:6.2.2

test:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test

pages:
  cache:
    paths:
      - public/content
  script:
    - npm run sync-content
    - npm run build
    - npm run build:minify
  artifacts:
    paths:
      - public
  only:
    - master
