image: node:8.5

cache:
  paths:
    - node_modules/
    - public/content
    - ~/.yarn-cache

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - npm run test-with-coverage

deploy_production:
  stage: deploy
  script:
    - yarn install
    - npm run sync-content
    - npm run build
    - npm run build:minify
    - npm run deploy:production
  only:
    - master
